
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnmapxxmswjaxiurqogj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubWFweHhtc3dqYXhpdXJxb2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Njk0ODAsImV4cCI6MjA2MzA0NTQ4MH0.UiBffmv1ER3b4v6N-tuLumwR-0vINQYOx8LvTQiD_e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
